serverAddr = 'bj.mefrp.yealqp.cn'
serverPort = 2333
user = '76d131d2ee4849a02177bf12419a9a0b'

[auth]
method = 'token'
token = 'MEFrpServerToken'

[[proxies]]
name = 'MC'
type = 'tcp'

localIP = '127.0.0.1'
localPort = 25565
remotePort = 45555

[proxies.transport]
useEncryption = false
useCompression = false